// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBct3VU6gtYUq0v3bhJ5LgjpdVWV7t6doI',
    appId: '1:113708571782:web:9b5138c01069b916fec507',
    messagingSenderId: '113708571782',
    projectId: 'aplikasi-batik-nasional',
    authDomain: 'aplikasi-batik-nasional.firebaseapp.com',
    databaseURL: 'https://aplikasi-batik-nasional-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-batik-nasional.appspot.com',
    measurementId: 'G-H1ZGTYBWX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBrUcxu6kMKqgUaZTjPiylf2SlA6FJerE',
    appId: '1:113708571782:android:e5a5757142d2fc0cfec507',
    messagingSenderId: '113708571782',
    projectId: 'aplikasi-batik-nasional',
    databaseURL: 'https://aplikasi-batik-nasional-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-batik-nasional.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1IscdqgHepNg5sBW7oIDylJfVtu0RSbg',
    appId: '1:113708571782:ios:42dfc69a2c3f24a2fec507',
    messagingSenderId: '113708571782',
    projectId: 'aplikasi-batik-nasional',
    databaseURL: 'https://aplikasi-batik-nasional-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-batik-nasional.appspot.com',
    iosClientId: '113708571782-7iralbql2ic1ba4309v7l30if1sjnead.apps.googleusercontent.com',
    iosBundleId: 'com.example.batikNasional',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1IscdqgHepNg5sBW7oIDylJfVtu0RSbg',
    appId: '1:113708571782:ios:42dfc69a2c3f24a2fec507',
    messagingSenderId: '113708571782',
    projectId: 'aplikasi-batik-nasional',
    databaseURL: 'https://aplikasi-batik-nasional-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-batik-nasional.appspot.com',
    iosClientId: '113708571782-7iralbql2ic1ba4309v7l30if1sjnead.apps.googleusercontent.com',
    iosBundleId: 'com.example.batikNasional',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBct3VU6gtYUq0v3bhJ5LgjpdVWV7t6doI',
    appId: '1:113708571782:web:230f8cfab3918546fec507',
    messagingSenderId: '113708571782',
    projectId: 'aplikasi-batik-nasional',
    authDomain: 'aplikasi-batik-nasional.firebaseapp.com',
    databaseURL: 'https://aplikasi-batik-nasional-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-batik-nasional.appspot.com',
    measurementId: 'G-LBXT6D76EN',
  );
}
